export const ORDER_STATUS = {
  ORDER_SUCCESS: 'ORDER_SUCCESS',
  PRODUCT_SETTING: 'PRODUCT_SETTING',
  SHIPPING: 'SHIPPING',
  DELIVERED: 'DELIVERED',
  CONFIRMED: 'CONFIRMED',
  CANCEL: 'CANCEL',
} as const;

export const ORDER_STATUS_STRING = {
  [ORDER_STATUS.ORDER_SUCCESS]: '주문완료',
  [ORDER_STATUS.PRODUCT_SETTING]: '상품준비',
  [ORDER_STATUS.SHIPPING]: '발송',
  [ORDER_STATUS.DELIVERED]: '배송완료',
  [ORDER_STATUS.CONFIRMED]: '확정',
  [ORDER_STATUS.CANCEL]: '취소',
};

export const ORDER_STATUS_PRIORITY = {
  [ORDER_STATUS.ORDER_SUCCESS]: 1,
  [ORDER_STATUS.PRODUCT_SETTING]: 2,
  [ORDER_STATUS.SHIPPING]: 3,
  [ORDER_STATUS.DELIVERED]: 4,
  [ORDER_STATUS.CONFIRMED]: 5,
  [ORDER_STATUS.CANCEL]: 6,
};

export const ORDER_STATUS_OPTIONS = [
  {
    value: [],
    label: '전체',
  },
  {
    value: [ORDER_STATUS.ORDER_SUCCESS],
    label: ORDER_STATUS_STRING[ORDER_STATUS.ORDER_SUCCESS],
  },
  {
    value: [ORDER_STATUS.PRODUCT_SETTING],
    label: ORDER_STATUS_STRING[ORDER_STATUS.PRODUCT_SETTING],
  },
  {
    value: [ORDER_STATUS.SHIPPING],
    label: ORDER_STATUS_STRING[ORDER_STATUS.SHIPPING],
  },
  {
    value: [ORDER_STATUS.DELIVERED],
    label: ORDER_STATUS_STRING[ORDER_STATUS.DELIVERED],
  },
  {
    value: [ORDER_STATUS.CONFIRMED],
    label: ORDER_STATUS_STRING[ORDER_STATUS.CONFIRMED],
  },
  {
    value: [ORDER_STATUS.CANCEL],
    label: ORDER_STATUS_STRING[ORDER_STATUS.CANCEL],
  },
];
