import BaseTypography from '@@components/Typography/BaseTypography';
import { TYPOGRAPHY_THEME } from '@@components/Typography/constants';

const Typography = {
  [TYPOGRAPHY_THEME.HEADLINE_1]: BaseTypography(TYPOGRAPHY_THEME.HEADLINE_1),
  [TYPOGRAPHY_THEME.HEADLINE_2]: BaseTypography(TYPOGRAPHY_THEME.HEADLINE_2),
  [TYPOGRAPHY_THEME.HEADLINE_3_24_EB]: BaseTypography(TYPOGRAPHY_THEME.HEADLINE_3_24_EB),
  [TYPOGRAPHY_THEME.HEADLINE_3_20_EB]: BaseTypography(TYPOGRAPHY_THEME.HEADLINE_3_20_EB),

  [TYPOGRAPHY_THEME.SUBTITLE_1]: BaseTypography(TYPOGRAPHY_THEME.SUBTITLE_1),

  [TYPOGRAPHY_THEME.BODY_1]: BaseTypography(TYPOGRAPHY_THEME.BODY_1),
  [TYPOGRAPHY_THEME.BODY_2]: BaseTypography(TYPOGRAPHY_THEME.BODY_2),
  [TYPOGRAPHY_THEME.BODY_3]: BaseTypography(TYPOGRAPHY_THEME.BODY_3),

  [TYPOGRAPHY_THEME.CAPTION_1]: BaseTypography(TYPOGRAPHY_THEME.CAPTION_1),
};

export default Typography;
