export const CREDIT_CARD_STRING: Record<string, string> = {
  AX: 'American Express',
  BC: 'Bank Card',
  BL: 'Carte Bleu',
  CB: 'Carte Blanche',
  DN: 'Diners Club',
  DS: 'Discover Card',
  EC: 'Eurocard',
  JC: 'Japanese Credit Bureau Credit Card',
  LC: 'Local Card',
  MA: 'Maestro',
  MC: 'Master Card',
  SO: 'Solo',
  CU: 'Union Pay',
  TP: 'Universal Air Travel Card',
  VE: 'Visa Electron',
  VI: 'Visa',
  CA: 'Master Card',
  DC: 'Diners Club',
  IK: 'Dankort',
  UP: 'Union Pay',
};
