# This is a basic workflow to help you get started with Actions
name: Rebase Check
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, reopened, synchronize]
    branches: ['**']
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check rebased
        run: |
          git checkout ${{ github.head_ref }}
          git checkout ${{ github.base_ref }}
          base_hash=$(git show-ref --heads -s ${{github.base_ref}} ) && pr_merge_hash=$(git merge-base ${{github.base_ref}} ${{github.head_ref}}) && ([ "${base_hash}" = "${pr_merge_hash}" ] && echo "Already rebased, merge-base commit  ${base_hash}" || exit 1)
